### ISSUE TITLE
issues don't have info on when they occur

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#11]
so when you click on the issue, it doesn't jump anywhere and it doesn't show the red highlight in the editor, just the issue is there and that's it

**Comment by laralove143** [comment]
so I did some testing and commenting the issue provider lines and relying on rust analyzer for everything works fine. the only weird thing is it takes about 20 seconds for it to start catching issues but after 20 secs everything works pretty instantly

**Comment by kilbd** [comment]
Interesting! That's not been what I've seen. When clicking on a manually provided issue in the Issues sidebar, it takes me to the section of the file with the issue and the text range of the issue has a subtle highlight (I'm using One Dark theme). If the line has been edited since being saved, then it doesn't have the typical issue highlight (red/yellow/blue underline with my theme) until saved again, but unaltered lines have issues highlighted in the editor.

<img width="680" alt="Screen Shot 2021-10-03 at 4 52 50 PM" src="https://user-images.githubusercontent.com/2053455/135771212-cbb3c0c1-a10d-4d44-832b-2e3dc5566355.png">

The reason I started manually providing issues on save was because I couldn't get issues to stay in sync when using Rust Analyzer. It would initially provide them, but fail to clear them when they were resolved and didn't always pick up new issues. Waiting any length of time and/or saving had no effect. I'd definitely prefer it if we could rely on Rust Analyzer for issues, though, especially since there's no way to manually provide Code Actions.

Let me take another look once I get installing the RA binary to the extension to work. I'm using a Homebrew installation of Rust Analyzer (recommended install method for macOS) – currently version __2021-09-20__.

**Comment by kilbd** [comment]
Sad to say I'm seeing the same behavior with a directly-downloaded binary (now version 2021-10-04). I'll keep looking into this.

**Comment by kilbd** [comment]
With version 2 of the extension, I switched to using Rust Analyzer for all issues as Panic seems to have resolved a lot of issues with their language server client. For this version I set the minimum Nova version to 9. If anyone is still using Nova and this extension, let me know if clicking an Issue doesn't bring up the code for that issue.
