### ISSUE TITLE
[BUG] code actions like import don't work

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#16]
**Describe the bug**
nothing happens when i run a code action

**To Reproduce**
1. press cmd+shift+a
2. select a code action
3. nothing happens

**Expected behavior**
the action actually works

**Versions (please complete the following information):**
 - macOS: Monterrey
 - Processor: Intel
 - Nova 8.3
 - Extension Version 1.0.5

**Comment by kilbd** [comment]
I know, it's super frustrating that code actions don't work because Rust Analyzer has some really handy ones. Unfortunately, this is a bug with Nova itself and I can't fix it. Extension devs brought it to Panic's attention many _months_ ago, but like other showstopper bugs with their LSP client (like #13 ) it remains unaddressed. It's really taken the wind out of my sails, and forced me to use other editors I don't really want to use.

Essentially, Nova's LSP client is registering a capability that it doesn't actually support (`documentChanges`), so Rust Analyzer is sending code actions in that format instead of the format Nova actually supports (`changes`). The fix _should_ be simply changing an initialization property from true to false – and this should fix it for other languages besides Rust as well – but Panic hasn't done that.

**Comment by laralove143** [comment]
wow.. it feels like panic kinda abandoned nova... what ide do you use btw

**Comment by kilbd** [comment]
Not so much abandoned as under-invested in Nova. There's a single developer working on it, which seems inadequate if they want to compete with other IDEs, but I'm sure they have a better grasp of the economics of the space and have their reasons. It does seem like 80%+ of the benefit of a code editor comes from syntax highlighting and code hints, though. The good news is that the developer seems to agree that LSP client improvements should get some focus in the near future, but didn't offer a more specific timeline than "soon."

Personally, I haven't settled on an IDE yet. I still use Nova for front end projects. I've used Sublime, but it feels like it has too much friction to get into a flow. I keep coming back to VS Code, but I don't like it. I really think Nova could mostly work for me if they could get their LSP house in order.

**Comment by laralove143** [comment]
i’ve never used sublime, never seemed that pretty to me, i’ve tried jetbrains (clion) and vscode but i keep coming back to nova, i go back and forth honestly. hopefully nova will get some proper support because i love it

**Comment by kilbd** [comment]
Nova 9 was released today, and Panic looks to have fixed this bug. Code Actions now work for me! For anyone still using Nova, try using version 9. I'll leave this issue open another week or so in case anyone has something to add.
