### ISSUE TITLE
[BUG] Formatting looks for rustfmt.toml in the wrong directory

### ISSUE THREAD

**Issue by edwardloveall** [kilbd/nova-rust#43]
**Describe the bug**

When formatting on save, my custom rustfmt settings set in `rustfmt.toml` at the root of the project are not respected. I think [this code in rust-formatter.ts](https://github.com/kilbd/nova-rust/blob/864947ad/src/rust-formatter.ts#L24-L27) is the culprit. If I do something similar in a javascript console I get the parent directory:

```js
const path = "/path/to/project-dir"
path.substring(0, path.lastIndexOf('/')) // returns '/path/to'
```

**To Reproduce**
1. `cargo new test-project`
2. `cd test-project`
3. `echo 'tab_spaces = 2' > rustfmt.toml` (or whatever format that's not standard)
4. Open project `nova .`
5. Ensure Format on save is enabled
6. Open `src/main.rs`
7. Save

**Expected behavior**

The 4-space indent becomes a 2-space indent

**Versions (please complete the following information):**
 - macOS: Ventura 13.3.1
 - Processor: Apple Silicon
 - Nova 10.6
 - Extension Version 2.3.1

**Additional context**

I was able to get this to work if I put the `rustfmt.toml` in the directory above my project directory. I thought that maybe the project was expecting the dir to have a slash at the end, so I tried opening it with `nova ./` instead of my normal `nova .` but that didn't help.

I also tried to run the extension locally, but typescript would not build on account of some mismatched nova types.

**Comment by kilbd** [comment]
Thank you for reporting this issue! Thanks also for all the detail and letting me know what you've tried. I'll admit I haven't been good about including a `rustfmt.toml` in recent projects so I didn't experience this bug. 😅

You were close to the source, but the real issue was [this conditional](https://github.com/kilbd/nova-rust/blob/864947ad/src/rust-formatter.ts#L80-L83). In one case I return the file path, and in another I return a directory path. I must have been careless when I tried to get format on save to find the Rust edition for the project (`rustfmt` defaults to 2015 edition for some reason).

Fix is coming shortly!

**Comment by edwardloveall** [comment]
Amazing, and thank _you!_ Updated and it works great. I'll close the issue.
