### ISSUE TITLE
Clippy Support

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#7]
it should work the same way, the issue parser already works with the json spec

**Comment by kilbd** [comment]
Right on! We should definitely add Clippy.

I'm thinking #6 will be the last feature I add before shipping Version 1. I want to get the current feature set out there and make sure there aren't major bugs before adding additional features. This will make a nice addition for v2.

**Comment by laralove143** [comment]
yes i agree! we definitely need some testing before publishing it. guess i’ll just use it as my daily driver

**Comment by winterqt** [comment]
Would you accept a PR adding this feature (with a bit more flexibility than described here, which is similar to how the Rust Analyzer VS Code extension does it)?

**Comment by winterqt** [comment]
> It sounds to me like a user preference to select either "check" or "clippy" as the command to run to surface issues.

This was basically what I was thinking, except Rust Analyzer's VS Code extension has this configurable by a string as opposed to a preset list of options (hence the point I made about flexibility).

<img width="535" alt="image" src="https://user-images.githubusercontent.com/78392041/143131928-5cb0eef7-dfe4-4f2e-b962-2ade28b6d57a.png">

**Comment by kilbd** [comment]
Preference added in extension version 2.0, which requires Nova 9 (released today). It can be adjusted per project.

I kept the preference as a radio selection instead of an open field. I believe this makes options more discoverable for newer users of Rust. If there are other commands I should add for save checks, please open a new issue!
